//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Хакатон.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABuilding
    {
        public string BuildinName { get; set; }
        public string Adres { get; set; }
        public System.DateTime yearBuld { get; set; }
        public string State { get; set; }
        public int FloorsCount { get; set; }
        public int FlatsCount { get; set; }
        public string Material { get; set; }
        public int CudNum { get; set; }
        public int Square { get; set; }
        public int PeopleCount { get; set; }
    }
}
