//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Хакатон.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJournal
    {
        public System.DateTime ADate { get; set; }
        public string Comment { get; set; }
        public string FIOEmpl { get; set; }
    }
}
